"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { getFeed } from "@/lib/api";

interface FeedItem {
  id: string;
  title: string;
  disease_area: string;
  novelty_score: number;
  created_at: string;
}

export default function FeedPage() {
  const [items, setItems] = useState<FeedItem[]>([]);
  const [diseaseFilter, setDiseaseFilter] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const data = await getFeed({
          disease_area: diseaseFilter || undefined,
          limit: 20,
        });
        setItems(Array.isArray(data) ? data : data.items || []);
      } catch {
        setItems([]);
      }
      setLoading(false);
    }
    load();
  }, [diseaseFilter]);

  return (
    <div className="mx-auto max-w-4xl px-6 py-12">
      <h1 className="mb-2 text-3xl font-bold text-slate-800">Discovery Feed</h1>
      <p className="mb-8 text-slate-500">
        Browse the latest hypotheses generated by Nexus.
      </p>

      {/* Filter Bar */}
      <div className="mb-6">
        <Input
          placeholder="Filter by disease area..."
          value={diseaseFilter}
          onChange={(e) => setDiseaseFilter(e.target.value)}
          className="max-w-sm"
        />
      </div>

      {/* Feed */}
      <div className="space-y-4">
        {loading && (
          <p className="text-sm text-slate-400">Loading discoveries...</p>
        )}
        {!loading && items.length === 0 && (
          <p className="text-sm text-slate-400">
            No discoveries found. Launch a session to generate hypotheses.
          </p>
        )}
        {items.map((item) => (
          <Link key={item.id} href={`/hypothesis/${item.id}`}>
            <Card className="cursor-pointer transition-shadow hover:shadow-md">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <Badge variant="secondary" className="bg-teal-50 text-teal-700">
                    {item.disease_area}
                  </Badge>
                  <span className="text-xs text-slate-400">
                    {new Date(item.created_at).toLocaleDateString()}
                  </span>
                </div>
                <CardTitle className="mt-2 text-base">{item.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2">
                  <div className="h-2 flex-1 rounded-full bg-slate-100">
                    <div
                      className="h-2 rounded-full bg-emerald-500"
                      style={{ width: `${(item.novelty_score || 0) * 100}%` }}
                    />
                  </div>
                  <span className="text-xs font-medium text-emerald-600">
                    {((item.novelty_score || 0) * 100).toFixed(0)}% novel
                  </span>
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
}
